#ifndef __LEECHCOREDEVS_H__
#define __LEECHCOREDEVS_H__
#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

typedef enum tdLEECHCORE_DEVICE {
	LEECHCORE_DEVICE_NA = 0,
	LEECHCORE_DEVICE_FILE = 1,
	LEECHCORE_DEVICE_PMEM = 2,
	LEECHCORE_DEVICE_FPGA = 3,
	LEECHCORE_DEVICE_SP605_TCP = 4,
	LEECHCORE_DEVICE_USB3380 = 5,
	LEECHCORE_DEVICE_TOTALMELTDOWN = 6,
	LEECHCORE_DEVICE_HVSAVEDSTATE = 7,
	LEECHCORE_DEVICE_RAWTCP = 8,
	//LEECHCORE_DEVICE_HVMM = 9,
} LEECHCORE_DEVICE;

#ifdef __cplusplus
}
#endif /* __cplusplus */
#endif /* __LEECHCORE_H__ */